version: '3'

services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - ${MINIO_DATA_VOLUME}:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSOWRD}
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001

networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true